version: '3'

services:
  dash:
    image: python:3.11
    restart: unless-stopped
    ports:
      - ${DASH_PORT:-8050}:8050
    volumes:
      - ./dash-app:/app
      - ./docker_entrypoint_dash.sh:/docker_entrypoint_dash.sh
      - ./run_dash_app.sh:/run_dash_app.sh
    environment:
      - DEBUG=${DEBUG:-true}
    working_dir: /app
    entrypoint: ["/docker_entrypoint_dash.sh"]
    command: ["/run_dash_app.sh"]
